version: '3.8'

services:
  superset-cont:
    build: .
    container_name: superset-cont
    environment:
      SUPERSET_SECRET_KEY: ujjawal_password
    volumes:
      - ./superset:/app/superset_home
    ports:
      - 9041:8088
    networks:
      - superset-network
    restart: always

  postgres-visualization:
    build: ./postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: ujjawaldbtpostgres
      POSTGRES_DB: postgresvisualization
    ports:
      - 9040:5432
    networks:
      - superset-network

networks:
  superset-network:
    driver: bridge
